### ISSUE TITLE
readme gifs are broken on vscode

### ISSUE THREAD

**Issue by Brianzchen** [flow/flow-for-vscode#433]
When you browse vscode to try and install this plugin the gifs are broken and give no context. This would be a very bad new dev experience.

Right now the link is [here](https://github.com/flowtype/flow-for-vscode/raw/master/readme/flow-main.gif) which gives 404

<img width="803" alt="Screen Shot 2021-10-01 at 7 00 05 am" src="https://user-images.githubusercontent.com/12436524/135529514-64545a6a-7ba4-4768-89a3-1e53f8602a6d.png">

**Comment by mroch** [comment]
this is because the branch was renamed to `main`. looks like we need to do a whole patch release just to update the marketplace? :/

**Comment by Brianzchen** [comment]
Hey @mroch this is still broken. Is someone from Facebook (meta) gonna fix this? Pretty sad experience for anyone who tries to install it first time

**Comment by mroch** [comment]
published 2.0.0 which fixed this
