### ISSUE TITLE
Flow unable to verify integrity

### ISSUE THREAD

**Issue by peachbits** [flow/flow-for-vscode#435]
I'm getting this error message from the extension when starting VSCode or restarting the Flow Client:

![Screen Shot 2022-03-21 at 3 41 25 PM](https://user-images.githubusercontent.com/41451710/159374846-3bd31375-0435-411f-889c-4f8d7035a69f.png)

And peaking into the extension output I see:

```
Info  - 3:38:36 PM - edge-react-gui/.flowconfig] restarting client
[Info  - 3:38:36 PM - edge-react-gui/.flowconfig] Unable to verify SHASUM256.txt.sign:
ENOENT: no such file or directory, open '/Users/Matthew/git/edge-react-gui/node_modules/flow-bin/SHASUM256.txt.sign'
[Error - 3:38:36 PM - edge-react-gui/.flowconfig] Error when verifying flow-bin in /Users/Matthew/git/edge-react-gui/node_modules/flow-bin:
Failed to find SHASUM256.txt line containing flow-osx-v0.84.0/flow
```

I peaked into the node_modules directory to see if the SHASUM256.txt file is present, and it is. However the `.txt.sign` file is not present.

I'm using Flow 0.84.0 in my project, and this didn't happen until updating macOS. Either a macOS security update is triggering this behavior, or it's a security update in VSCode. Does anyone have any insight into this issue?

**Comment by samwgoldman** [comment]
Hi Matthew,

Please see the [Changelog](https://github.com/flow/flow-for-vscode/blob/main/CHANGELOG.md#210-2022-03-15) for flow-for-vscode version 2.1.0.

**Comment by peachbits** [comment]
Got it, thanks!
