### ISSUE TITLE
Vscode does not check continuously and get only the first state

### ISSUE THREAD

**Issue by vidongls** [flow/flow-for-vscode#443]
First time check:
![image](https://user-images.githubusercontent.com/59497657/185092727-ae78dd44-a009-4186-8020-649c4799d9b5.png)
Next time don't check
![image](https://user-images.githubusercontent.com/59497657/185092809-23ddc5e9-01d6-4671-bc2b-0c976210185f.png)

.babelrc
{
	"presets": ["@babel/preset-flow"]
}

.flowconfig
[ignore]
<PROJECT_ROOT>/node_modules/.*
<PROJECT_ROOT>/node_modules/test/resolver/malformed_package_json/.*
<PROJECT_ROOT>/node_modules/*
<PROJECT_ROOT>/build/.*
[include]

[libs]

[lints]

[options]

[strict]

I'm having trouble using not checking and only checking once. And the server is stopped continuously

**Comment by mroch** [comment]
sorry for the bad experience! a couple requests to help debug:

what OS are you using?
can you check the logs for any exceptions or at least why the server exited? *.log and *.monitor_log in /tmp/flow/ on Linux/Mac or C:\Users\you\AppData\Local\Temp\flow\ on Windows

**Comment by vidongls** [comment]
> sorry for the bad experience! a couple requests to help debug:
> 
> what OS are you using? can you check the logs for any exceptions or at least why the server exited? *.log and *.monitor_log in /tmp/flow/ on Linux/Mac or C:\Users\you\AppData\Local\Temp\flow\ on Windows
[DzCzBLearnJszBtestflow.log](https://github.com/flow/flow-for-vscode/files/9363552/DzCzBLearnJszBtestflow.log)
I am using Window Os.  I am having very bad experience using flowjs. 
I hope this problem is solved so I can use it. Thanks

**Comment by psychobolt** [comment]
Possibly related: https://github.com/facebook/flow/issues/8932
