### ISSUE TITLE
Using flow-for-vscode with old versions of flow-bin breaks functionality

### ISSUE THREAD

**Issue by Crzech** [flow/flow-for-vscode#445]
I've been trying to set flow-for-vscode to work with a project that has the following .flowconfig version:
```
[version]
0.181.1
```

Current flow-for-vscode-version:
`2.2.0`

Extension config:
``` 
"flow.pathToFlow": "./node_modules/.bin/flow",
"flow.useBundledFlow": false,
"flow.useNPMPackagedFlow": true
```

flow-bin version in package.json:
`"flow-bin": "0.181.1"`

Error I'm getting:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/27091230/188755289-b9b98cf9-4202-48b5-bb28-e482d4466791.png">

**Comment by SamChou19815** [comment]
@Crzech Does running flow stop and reload the window help resolving the problem?

**Comment by mroch** [comment]
Is flow-bin installed? The extension tries pathToFlow, but falls back if it's not there. But also since your pathToFlow is the same as it'd be from npm, I'd suggest not setting pathToFlow

**Comment by Crzech** [comment]
Hi @SamChou19815, I'm going to try restarting my computer since this was the output after running `./node_modules/.bin/flow stop`:
```
Trying to connect to server for `/home/cmontufar/code/pinboard/webapp`
Attempting to meanly kill server for `/home/cmontufar/code/pinboard/webapp`
Unable to figure out pids of running Flow server. Try manually killing it with 'pkill flow' (be careful on shared devservers)
```

**Comment by Crzech** [comment]
Hello @mroch, yes I have flow installed in the root of my project:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/27091230/188758677-392b3d9c-d3f5-4241-a2af-cd8fb5fcf7c4.png">
I'm going to remove `pathToFlow` setting and see if it makes any difference

**Comment by SamChou19815** [comment]
I will close this for now assuming the issue has been resolved, since there wasn't any new activities for a while. Feel free to reopen if issues persist.
