### ISSUE TITLE
Couldn't find version of node_modules/flow-bin/flow-osx-v0.142.0/flow

### ISSUE THREAD

**Issue by timBm10c** [flow/flow-for-vscode#455]
Hi,
I have installed flow in a local project and added the VS Code extension Flow Language Support. The extension is throwing this error:

Failed to start flow Error: Couldn't find version of `node_modules/flow-bin/flow-osx-v0.142.0/flow`

I have checked the path and the flow binary is in this location, so I don't understand what it's complaining about.

Thanks in advance.

Hi,
I have installed flow in a local project and added the VS Code extension Flow Language Support. The extension is throwing this error:

Failed to start flow Error: Couldn't find version of `node_modules/flow-bin/flow-osx-v0.142.0/flow`

I have checked the path and the flow binary is in this location, so I don't understand what it's complaining about.

Thanks in advance.

Also this may or may not be related, but when I run `yarn flow` I get the following error:

yarn run v1.22.21
$ /your/project/path/node_modules/.bin/flow
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at Object.<anonymous> (/your/project/path/node_modules/flow-bin/cli.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

Node.js v21.6.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by SamChou19815** [comment]
I believe this might be a result of macos ARM vs x86 mismatch.
I couldn't repro it myself, but does a solution like this help:
https://github.com/puppeteer/puppeteer/issues/9142#issuecomment-1535455712

**Comment by timBm10c** [comment]
Ah that worked, thanks!
