### ISSUE TITLE
Component syntax is not enabled

### ISSUE THREAD

**Issue by neutraali** [flow/flow-for-vscode#456]
Using `flow-bin@0.235.1` we're encountering a situation where we can't use the new [component syntax](https://flow.org/en/docs/react/component-syntax/) promised by the newer versions of **Flow**. After searching for pretty much a whole workday I couldn't find a single instance of this issue. How do we "enable" the component syntax?

![unsupported-syntax](https://github.com/flow/flow-for-vscode/assets/16540190/da03601d-7214-4b7a-9f38-0a0f6f2bacb2)

**Comment by panagosg7** [comment]
Apologies for the confusion. You can add enable this feature with
```
experimental.component_syntax=true
```
Will update the docs with this.

**Comment by SamChou19815** [comment]
The docs have been updated
