### ISSUE TITLE
[Request] Support for JavaScript in html files?

### ISSUE THREAD

**Issue by JdKock** [flow/flow-for-vscode#71]
Is it possible to add support for javascript in html files ?

I'm using Polymer to building Web Components and it would be nice if I can use this extensions to check the javascript in the html files.

**Comment by orta** [comment]
This extension does register for the [javascript](https://github.com/flowtype/flow-for-vscode/blob/master/package.json#L15-L18) scope, so I would have expected it to work - does flow work correctly via the CLI inside that kind of scope?

**Comment by JdKock** [comment]
If I put the following code line a html file, test-component.html, and I start flow from the command line. It give as a result : No errors!
I think flow don't work for javascript between the <script> tags in a html file.
````
<dom-module id="test-component">
  <template>
    <h1>Hello World</h1>
  </template

  <script>
    // @flow

    Polymer({
      is: 'test-component',

      ready: function () {
        var str: number = 'hello world!';
      }
    });
  </script>
</dom-module>
````

**Comment by orta** [comment]
That's fair, we won't be able to support it without flow itself supporting the feature I'm afraid.
