### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by misantronic** [flow/flow-for-vscode#76]
The Code Completion and navigating is not quite working as expected.
I define my types in an external folder. When I dont open these files, VS will not know where these types are stored. And even when the type-declaration-file is open, not all properties are found.

Please see the attached screenshots for clarification.

Types are not found by default:
<img width="559" alt="screen shot 2017-02-04 at 16 33 56" src="https://cloud.githubusercontent.com/assets/6033531/22619599/4b6738d0-eaf8-11e6-9333-5baf3d28e681.png">

TState-file is open and types are partially found:
<img width="260" alt="screen shot 2017-02-04 at 16 36 06" src="https://cloud.githubusercontent.com/assets/6033531/22619601/54e31cd0-eaf8-11e6-93a6-3e21173b70d2.png">
<img width="532" alt="screen shot 2017-02-04 at 16 36 16" src="https://cloud.githubusercontent.com/assets/6033531/22619600/54e2f958-eaf8-11e6-9cfe-b93b91a8e655.png">

Is this maybe because the code is in a decorator? `@connect`

**Comment by orta** [comment]
Do you get the same results from Atom? It might be a flow (parser) limitation around that decorator
